import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fiddler on The Roof.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Fiddle.</h1>
        <div className={styles.root_index_description}>
          This is some text that is going to live inside of this section tag. This content is not meant to mean anything nor is it meant to be permanent, in fact, it is only filler text. This is some text that is going to live inside of this section tag. This content is not meant to mean anything nor is it meant to be permanent, in fact, it is only filler text.
        </div>
      </main>
    </div>
  )
}